import mongoose from "mongoose";
import dotenv from "dotenv";
import Lead from "./models/LeadSchema.js";

dotenv.config();

mongoose
  .connect(process.env.MONGO)
  .then(() => console.log("✅ Connected to MongoDB"))
  .catch((err) => console.log("❌ MongoDB connection error:", err));

const sampleLeads = [
  {
    lead: "John Doe",
    email: "johndoe@example.com",
    stage: "Lead",
    date: "2024-02-05",
    name: "John Doe",
    company: "TechCorp",
    joinDate: "2023-06-15",
    jobTitle: "Software Engineer",
    industry: "Technology",
    location: "New York",
    phone: "+1-555-1234",
    social: "https://linkedin.com/in/johndoe",
  },
  {
    lead: "Jane Smith",
    email: "janesmith@example.com",
    stage: "Discovery Call",
    date: "2024-02-10",
    name: "Jane Smith",
    company: "InnovaSoft",
    joinDate: "2023-09-20",
    jobTitle: "Project Manager",
    industry: "Finance",
    location: "Los Angeles",
    phone: "+1-555-5678",
    social: "https://linkedin.com/in/janesmith",
  },
  {
    lead: "Michael Johnson",
    email: "michaeljohnson@example.com",
    stage: "Quote",
    date: "2024-02-15",
    name: "Michael Johnson",
    company: "GreenEnergy",
    joinDate: "2023-02-12",
    jobTitle: "Sales Executive",
    industry: "Healthcare",
    location: "Chicago",
    phone: "+1-555-9876",
    social: "https://linkedin.com/in/michaeljohnson",
  },
  {
    lead: "Emily Brown",
    email: "emilybrown@example.com",
    stage: "Proposal",
    date: "2024-02-20",
    name: "Emily Brown",
    company: "HealthPlus",
    joinDate: "2023-11-05",
    jobTitle: "HR Manager",
    industry: "Education",
    location: "San Francisco",
    phone: "+1-555-4321",
    social: "https://linkedin.com/in/emilybrown",
  },
  {
    lead: "David Wilson",
    email: "davidwilson@example.com",
    stage: "Negotiation",
    date: "2024-02-25",
    name: "David Wilson",
    company: "EduWorld",
    joinDate: "2023-07-22",
    jobTitle: "Marketing Director",
    industry: "Retail",
    location: "Seattle",
    phone: "+1-555-2468",
    social: "https://linkedin.com/in/davidwilson",
  },
  {
    lead: "Olivia Martinez",
    email: "oliviamartinez@example.com",
    stage: "On-boarding",
    date: "2024-03-01",
    name: "Olivia Martinez",
    company: "AutoTech",
    joinDate: "2023-05-10",
    jobTitle: "Operations Manager",
    industry: "Automotive",
    location: "Austin",
    phone: "+1-555-1357",
    social: "https://linkedin.com/in/oliviamartinez",
  },
  {
    lead: "Liam Anderson",
    email: "liamanderson@example.com",
    stage: "Lead",
    date: "2024-02-28",
    name: "Liam Anderson",
    company: "FinServe",
    joinDate: "2023-08-30",
    jobTitle: "Financial Analyst",
    industry: "Finance",
    location: "Boston",
    phone: "+1-555-7890",
    social: "https://linkedin.com/in/liamanderson",
  },
  {
    lead: "Sophia Lewis",
    email: "sophialewis@example.com",
    stage: "Discovery Call",
    date: "2024-03-05",
    name: "Sophia Lewis",
    company: "WellnessCo",
    joinDate: "2023-03-14",
    jobTitle: "Wellness Coordinator",
    industry: "Healthcare",
    location: "San Diego",
    phone: "+1-555-3698",
    social: "https://linkedin.com/in/sophialewis",
  },
  {
    lead: "James Carter",
    email: "jamescarter@example.com",
    stage: "Quote",
    date: "2024-03-10",
    name: "James Carter",
    company: "RetailKing",
    joinDate: "2023-09-18",
    jobTitle: "Retail Manager",
    industry: "Retail",
    location: "Denver",
    phone: "+1-555-7412",
    social: "https://linkedin.com/in/jamescarter",
  },
  {
    lead: "Charlotte Hernandez",
    email: "charlottehernandez@example.com",
    stage: "Proposal",
    date: "2024-03-12",
    name: "Charlotte Hernandez",
    company: "BuildIt",
    joinDate: "2023-07-25",
    jobTitle: "Construction Lead",
    industry: "Construction",
    location: "Phoenix",
    phone: "+1-555-8524",
    social: "https://linkedin.com/in/charlottehernandez",
  },
  {
    lead: "Henry Miller",
    email: "henrymiller@example.com",
    stage: "Negotiation",
    date: "2024-03-15",
    name: "Henry Miller",
    company: "EcoSolutions",
    joinDate: "2023-06-20",
    jobTitle: "Environmental Consultant",
    industry: "Energy",
    location: "Philadelphia",
    phone: "+1-555-9635",
    social: "https://linkedin.com/in/henrymiller",
  },
  {
    lead: "Isabella Scott",
    email: "isabellascott@example.com",
    stage: "On-boarding",
    date: "2024-03-18",
    name: "Isabella Scott",
    company: "EdTech",
    joinDate: "2023-02-11",
    jobTitle: "Learning Specialist",
    industry: "Education",
    location: "Dallas",
    phone: "+1-555-7536",
    social: "https://linkedin.com/in/isabellascott",
  },
  {
    lead: "William Thomas",
    email: "williamthomas@example.com",
    stage: "Lead",
    date: "2024-03-20",
    name: "William Thomas",
    company: "DataSecure",
    joinDate: "2023-12-01",
    jobTitle: "Cybersecurity Analyst",
    industry: "Technology",
    location: "Miami",
    phone: "+1-555-1597",
    social: "https://linkedin.com/in/williamthomas",
  },
  {
    lead: "Mia Rodriguez",
    email: "miarodriguez@example.com",
    stage: "Discovery Call",
    date: "2024-03-22",
    name: "Mia Rodriguez",
    company: "FashionNova",
    joinDate: "2023-04-21",
    jobTitle: "Fashion Designer",
    industry: "Retail",
    location: "Las Vegas",
    phone: "+1-555-2589",
    social: "https://linkedin.com/in/miarodriguez",
  },
];

const seedDatabase = async () => {
  try {
    await Lead.deleteMany(); // ✅ Clear existing data
    await Lead.insertMany(sampleLeads);
    console.log("Sample Leads Added Successfully!");
    mongoose.connection.close();
  } catch (error) {
    console.error("Error seeding database:", error);
  }
};

seedDatabase();
